name: Deploy to DigitalOcean

on:
  push:
    branches:
      - development
      - qa

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up SSH
      uses: webfactory/ssh-agent@v0.5.3
      with:
        ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

    - name: Deploy to server
      run: |
        ssh root@45.55.125.31 << 'EOF'
          cd /var/www/startupproject
          
          # Pull the latest changes for the current branch
          git pull origin ${{ github.ref_name }}

          # Update the environment directories based on the branch
          if [[ "${{ github.ref_name }}" == "development" ]]; then
            echo "Deploying to Development Environment"
            cp -r * /var/www/startupproject/development
          fi
          if [[ "${{ github.ref_name }}" == "qa" ]]; then
            echo "Deploying to QA Environment"
            cp -r * /var/www/startupproject/qa
          fi
        EOF
