name: Deploy to DigitalOcean (Development)

on:
  push:
    branches:
      - development  # Ensures this runs only when pushing to development

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Deploy via SSH
        uses: appleboy/ssh-action@v0.1.10
        with:
          host: 45.55.125.31
          username: root
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            cd /var/www/[dev.startupproject.me]
            git pull origin development
            sudo systemctl restart nginx

